version: "3"

services: 
  gander:
    build:
      args:
        user: gander
        uid: 1001
      context: .
      dockerfile: Dockerfile
    image: gander
    container_name: gander
    ports: 
      - '8080:8080'
    restart: unless-stopped
